#!/bin/bash

# 进入指定的目录
cd /root/SoruxNode/chat-$(read -p "请输入节点ID: " node_id && echo $node_id)

# 删除配置文件
rm config/session.json

# 停止并删除当前的docker-compose服务
docker-compose stop
docker-compose rm -f

# 创建新的session.json文件
echo "请输入refreshCookie: "
read refreshCookie
cat > config/session.json << EOF
{
  "refreshCookie": "$refreshCookie"
}
EOF

# 启动docker-compose服务
docker-compose up
